name: Setup for Node CI

runs:
  using: 'composite'
  steps:
    - name: Checkout
      uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: '16.13.0'
    - uses: actions/cache@v3
      id: cache-node
      with:
        path: ./node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-node-
    - name: Install dependencies
      run: yarn install
      shell: bash
