name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    name: Frontend build and deploy
    runs-on: ubuntu-latest
    env:
      REACT_APP_API_URL: ${{ secrets.REACT_APP_API_URL }}
      BASIC_USERNAME: ${{ secrets.BASIC_USERNAME }}
      BASIC_PASSWORD: ${{ secrets.BASIC_PASSWORD }}
      E2E_TEST_BASE_URL: ${{ secrets.E2E_TEST_BASE_URL }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: ./.github/actions/setup-node
      - name: Build
        run: yarn build
      # - name: Configure AWS Credentials
      #   uses: aws-actions/configure-aws-credentials@v1
      #   with:
      #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     aws-region: ap-northeast-1
      # - name: Deploy to S3
      #   run: aws s3 sync ./dist/ s3://art-s3 --delete
